version: 2
jobs:
  build:
    docker:
      - image: ninjaahhh/circleci-goquarkchain:v0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      # Build qkchash c++
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: go test -v ./... -gcflags=-l
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
